// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrnaWeb.Data;

namespace UrnaWeb.Migrations
{
    [DbContext(typeof(UrnaWebContext))]
    partial class UrnaWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("UrnaWeb.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateRegister");

                    b.Property<string>("VicePresident");

                    b.Property<int>("subtitle");

                    b.HasKey("Id");

                    b.ToTable("Candidate");
                });

            modelBuilder.Entity("UrnaWeb.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateRegister");

                    b.Property<int?>("IdCanditadeId");

                    b.HasKey("Id");

                    b.HasIndex("IdCanditadeId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("UrnaWeb.Models.Vote", b =>
                {
                    b.HasOne("UrnaWeb.Models.Candidate", "IdCanditade")
                        .WithMany("Votes")
                        .HasForeignKey("IdCanditadeId");
                });
#pragma warning restore 612, 618
        }
    }
}
